FROM docker:29.6.2-cli@sha256:be132a9f282288de4afaf63379dff75711fda0147c6b72a9df44e51841402144

RUN apk add --no-cache \
    bash=5.3.9-r1 \
    coreutils=9.11-r0 \
    cpio=2.15-r0 \
    findutils=4.10.0-r1 \
    gzip=1.14-r2 \
    nodejs=24.18.1-r0 \
    npm=11.12.1-r0 \
    tar=1.35-r5 \
    xorriso=1.5.8-r0

WORKDIR /repo
ENTRYPOINT ["/bin/bash", "/repo/factory/build-windows-container.sh"]
