#!/usr/sbin/nft -f

flush ruleset

table inet rinir_filter {
    chain input {
        type filter hook input priority filter; policy drop;

        iifname "lo" accept
        ct state established,related accept
        ct state invalid drop

        iifname "rinir-mgmt" udp sport 67 udp dport 68 accept
        iifname "rinir-mgmt" tcp dport 443 accept
        iifname "rinir-mgmt" ip protocol icmp accept
        iifname "rinir-mgmt" meta l4proto 58 accept

        iifname "rinir-modbus" ip protocol icmp accept
    }

    chain forward {
        type filter hook forward priority filter; policy drop;
        jump docker_forward
    }

    chain docker_forward {
        ct state established,related accept
        iifname "docker0" accept
        iifname "br-*" accept
        iifname "lo" oifname "docker0" accept
        iifname "lo" oifname "br-*" accept
    }

    chain output {
        type filter hook output priority filter; policy accept;
    }
}
